name: Dependencias entre jobs

on:
  push:
      branches: ["master"]

jobs:
  primer_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        uses: echo "Hola mundo"
  
  segudno_job:
    #Directivas de los jobs
    needs: primer_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        uses: echo "Hola mundo del segundo Job"




