name: Dependencias entre jobs

on:
  push:
      branches: ["master"]

jobs:
  primer_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola mundo"
  
  segundo_job:
    #Directivas de los jobs
    needs: primer_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola mundo del segundo Job"




