# Nombre del worflow
name: "Hola mundo"

# Trigger --> disparador del workflow
on:
  push:
      branches: ["master"]

# Jobs --> tareas que se ejecutan en el workflow
jobs:
  deploy-practica:
    # Runners --> Maquina virtual de github donde se ejecutara el job
    runs-on: ubuntu-latest

    # Pasos que se ejecutan en el job
    steps:
      - name: "Pull de c贸digo"
        uses: actions/checkout@v2

      - name: "Instalaci贸n de Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: "Instalaci贸n de dependencias"
        run: npm install

      - name: "Ejecuci贸n de pruebas"
        run: npm test


